env:
  browser: true
  es2020: true
  node: true
plugins:
  - svelte3
extends:
  - eslint:recommended
overrides:
  - files:
    - "**/*.svelte"
    processor: svelte3/svelte3

parserOptions:
  ecmaVersion: 11
  sourceType: module
rules:
  max-len:
    - 1
    - code: 120
      tabWidth: 2
